### PR TITLE
Update jsweet gradle plugin to use the latest jsweet version

### PR DESCRIPTION
**Pull request by angexis**
I also restored the gradle/ folder so that ./gradlew or ./gradlew.bat works out of the box

### CODE REVIEW

**Comment by lgrignon** [comment]
Thanks for your help!

**Comment by angexis** [comment]
You're welcome! Thanks for merging!

I was wondering if we could make the plugin agnostic from the used jsweet version: the jsweet plugin version would only be bumped if you add a feature to the plugin itself, while the JSweet version would be specified by the calling build.gradle. Not so sure how to achieve this. I haven't been "gradle-ing" seriously for a while so I would need to refresh my mind...

**Comment by lgrignon** [comment]
Same for me, haven't been gradle-ing for a while :) However, options are currently strongly tied to the transpiler's version so it would be very complicated to have a plugin working with all versions of the transpiler.
It would require some kind of generic transpiler options handling which is not available for now in the JSweet transpiler.
Still, it's not a bad idea. I would think about it in the near future.

**Comment by lgrignon** [comment]
One option could be to call the command line directly but actually I eventually think that it is good to keep the type and options checking.
We will keep the gradle & maven plugin in sync with version after each release.

**Pull request merged**
